### ISSUE TITLE
tid1500writer fails if value string too long

### ISSUE THREAD

**Issue by michaelschwier** [QIICR/dcmqi#316]
If the "value" entry for a measurement item has more than 16 characters the conversion fails. The failing call is [this](https://github.com/QIICR/dcmqi/blob/3f6534e16e09422b236690a9815e9ac33dc58f9a/apps/sr/tid1500writer.cxx#L215), however, the actual root of the problem is [this call](https://github.com/QIICR/dcmqi/blob/3f6534e16e09422b236690a9815e9ac33dc58f9a/apps/sr/tid1500writer.cxx#L213) creating the `numValue` object. For setting up `numValue`'s internal values, the constructor goes deep into DCMTK and eventually calls `DcmByteString::checkStringValue` (called from dcvrds.cc, defined in dcbytstr.cc) with a hard-coded length-limit of 16. Hence the initialization of `numValue` is incomplete and as a result the following call fails when checking the validity of `numValue`.

I assume the reason for the limit of 16 is that this is about the decimal digit precision limit of type double. However this is not transparent to the user (I only found it through a painful debugging session ;) ). 

I would suggest to either accept values longer than 16 digits (and the possible precision loss when storing them) and issue a warning to the user about the precision loss, or at least clearly state in the error message that this is the problem. However, in the latter case, the user might be forced to use e-notation for very large/small numbers (which are probably not even relevant in practice, should change unit instead). Also not sure if e-notation is supported by DCMTK?

**Comment by pieper** [comment]
The 16 character limit is probably because it's a DS VR (see table 6.2.1 linked below).  I agree this should be caught and fixed earlier in the code (ideally in a schema validation that checks the validity of the rest of the fields).

http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

**Comment by fedorov** [comment]
Yes, it makes sense to add it to the schema.

**Comment by jriesmeier** [comment]
It's true that (by default) the constructor of TID1419_ROIMeasurements_Measurement checks the passed values for validity (parameter "check" is true). And it's also true that the restrictions of the DICOM value representation DS (Decimal String) apply, which limits the value length to 16 bytes. @michaelschwier The scientific notation of numeric values is, of course, also supported by the DCMTK.

@fedorov If you want to get a more appropriate error code (than simply valid or invalid) you could use TID1419_ROIMeasurements_Measurement::createNewMeasurement() which returns a OFCondition instance instead of using the constructor of this class. But maybe it's easier to check the passed values in advance.

With regard to XML schema validation of DS values, you might want to have a look at [DCMTK's XML Schema for Structured Reporting](http://git.dcmtk.org/?p=dcmtk.git;a=blob;f=dcmsr/data/dsr2xml.xsd;h=7b5702dde770fa71185db5f1ae223fd2a4cdef96;hb=HEAD#l875).

**Comment by malaterre** [comment]
Just for historical reference you need to get a version of dsr2xml.xsd after commit [875181643364](http://git.dcmtk.org/?p=dcmtk.git;a=commitdiff;h=875181643364)

**Comment by fedorov** [comment]
Thanks for reminding me about this. 

The underlying issue was fixed in https://github.com/QIICR/dcmqi/commit/4804c84db76ab550469fa05eb3ad0703742a3fa9 (now JSON parameterizing SR conversion is using DS VR, and DS VR definition has the proper constraints in place).

The input JSON can be validated against the schema with ajv, and indeed properly reports the error for the situation that Michael encountered:

![image](https://user-images.githubusercontent.com/313942/46219846-5fdfcf00-c316-11e8-9b18-d3668527b22a.png)

![image](https://user-images.githubusercontent.com/313942/46219872-7d149d80-c316-11e8-9fda-9bf14232a15f.png)

It would be nice if we could validate JSON directly in the converter, instead of relying on user to find instructions and run ajv, but that is a separate project for which I do not have resources at the moment.
