### ISSUE TITLE
How to create a Dicom Seg in fractional mode?

### ISSUE THREAD

**Issue by jsmastro** [QIICR/dcmqi#467]
Hello,

Is it possible to convert ITK images to fractional Dicom Seg? If so, could you please provide an example? I have a segmentation expressed as a probability map and I would like to save it in Dicom format before applying a threshold to produce a binary segmentation.

Thanks!

**Comment by fedorov** [comment]
This is not supported currently in dcmqi, and due to limited resources, I do not know if/when I might have time to add this feature.

I recommend you look into highdicom: https://github.com/ImagingDataCommons/highdicom. You will probably need to write some code, but it might be easier to accomplish than adding functionality to dcmqi (in particular, since it is in python and not in c++).

**Comment by jsmastro** [comment]
Hello Andrey,
Thanks a lot for your response, I will take a look at highdicom.
Best regards,
