### ISSUE TITLE
Bad looking image after conversion, error in loading image

### ISSUE THREAD

**Issue by gladomat** [QIICR/dcmqi#494]
I used this command:

``` shell
./itkimage2segimage` --verbose --inputDICOMDirectory dcm/  \
--inputMetadata head.json \
--inputImageList segmentation.nrrd \
--outputDICOM threshold_head.dcm
```

After some errors that I fixed with your FAQ, I finally got this image

![image](https://github.com/QIICR/dcmqi/assets/17472969/5f474d2b-5af2-4cc2-ba2b-026bb98fa489)

Which looks terrible, and if I try to load it with ITK-Snap I get an error: 
![image](https://github.com/QIICR/dcmqi/assets/17472969/c4e2eb7b-bbdc-4250-9058-812aa0d3ea8f)
`Unhandled PixelFormat`

What am I doing wrong?

Here's the metadata

``` json
{
  "ContentCreatorName": "Reader1",
  "ClinicalTrialSeriesID": "Session1",
  "ClinicalTrialTimePointID": "1",
  "SeriesDescription": "Segmentation",
  "SeriesNumber": "300",
  "InstanceNumber": "1",
  "BodyPartExamined": "HEAD",
  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentDescription": "whole head",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "SimpleITK",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "69536005",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Head"
        },
        "recommendedDisplayRGBValue": [
          43,
          196,
          37
        ]
      }
    ]
  ],
  "ContentLabel": "SEGMENTATION",
  "ContentDescription": "Image segmentation",
  "ClinicalTrialCoordinatingCenterName": "dcmqi"
}
```

**Comment by fedorov** [comment]
@gladomat I am sorry for missing your question earlier. Looking at the screenshot, it is most likely the case that ITK-Snap/GDCM does not support the single bit encoding used in DICOM SEG.

You can report this issue and share a sample with the ITK-Snap developers and ask them to add this functionality.

In the meantime, you can use 3D Slicer to work with DICOM SEG: https://www.slicer.org/. In order to load DICOM SEG in Slicer you will first need to install QuantitativeReporting extension: https://qiicr.gitbook.io/quantitativereporting-guide/user-guide/installation-and-upgrade.

Please let me know if you need any further help and cannot load resulting segmentations in Slicer!
