### ISSUE TITLE
Establish a mechanism to communicate key parameters

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#54]
Specific example: how to communicate which b-values were used for model fit?

Awaiting suggestions from @dclunie

**Comment by dclunie** [comment]
If one is encoding an ADC map as an MR or Enhanced MR or Parametric Map IOD, then one can use the RWVM Quantity Definition Sequence to encode one or more items, one of which is the Quantity itself, and others of which can describe the method of calculation and/or its (numeric) parameters, and would could encode the numeric parameters to describe the b-values of the original images. E.g., for an ADC map calculated from B0 and B1000 source images using a mono-exponential model one might encode something like:

(G-C1C6, SRT, "Quantity") = (113041, DCM, "Apparent Diffusion Coefficient")
(G-C036, SRT, "Measurement Method") = (xxxx0, 99XXX, "Monoexponential ADC from log of ratio of two samples")
(xxxx1, 99XXX, "Source image diffusion b-value") = 0
(xxxx1, 99XXX, "Source image diffusion b-value") = 1000

I have pre-coordinated the concepts of both the "source image" and the "diffusion b-value" into one code to use as the concept name of the numeric parameter, because we don't have a way to post-coordinate these to allow re-use of a code for just "b-value"; arguably we could just omit the "source image" component of the concept and just send "b-value" and the recipient could assume it was an input parameter (in the general case, this would reduce the combinatorial explosion of pre-coordinated codes).

Arguably one could omit mention of the b-value = 0 parameter, but in reviewing the old literature, I see that in the classic Burdette paper [1], a b-value of 1, not 0, was used.

Even some of the more complicated methods of computing ADC maps, such as these that involve different B values on a voxelwise basis, could be represented this way  by listing all the collected b-values, even though one could not indicate which were used for which voxel (which would require another map). E.g., we might need methods such as:

"Monoexponential ADC from least squares fit of multiple samples"
"Monoexponential ADC from voxelwise selection of b-value"

See also [3].

Anyway, we should probably write a DICOM CP to add standard codes for the various methods and parameters.

We should probably consult with an MR physicist like Tom Chenevert and/or the QIBA MRI PDF group, to prepare a good list of methods and make sure we have captured the necessary parameters.

Before I forget to mention in, we also need to send the correct units in Measurement Units Code Sequence, which in UCUM are "mm2/s" (assuming all scaling issues have been appropriately dealt with [4], as should be the case for images you are creating).

David

1. Burdette JH, Elster AD, Ricci PE. Calculation of apparent diffusion coefficients (ADCs) in brain using two-point and six-point methods. J Comput Assist Tomogr. 1998 Oct;22(5):792–4. Available from: http://www.u.arizona.edu/~lewell/adc/article.html

2. Gatidis S, Schmidt H, Martirosian P, Nikolaou K, Schwenzer NF. Apparent diffusion coefficient-dependent voxelwise computed diffusion-weighted imaging: An approach for improving SNR and reducing T2 shine-through effects. Journal of Magnetic Resonance Imaging. 2016;43(4):824–32. Available from: http://dx.doi.org/10.1002/jmri.25044

3. Park MY, Byun JY. Understanding the Mathematics Involved in Calculating Apparent Diffusion Coefficient Maps. American Journal of Roentgenology. 2012 Dec 1;199(6):W784–W784. Available from: http://dx.doi.org/10.2214/AJR.12.9231

4. Chenevert TL, Malyarenko DI, Newitt D, Li X, Jayatilake M, Tudorica A, et al. Errors in Quantitative Image Analysis due to Platform-Dependent Image Scaling. Translational Oncology. 2014 Feb;7(1):65–71. Available from: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3998685/

**Comment by dclunie** [comment]
If one is encoding an ADC map as an MR or Enhanced MR or Parametric Map 
IOD, then one can use the RWVM Quantity Definition Sequence to encode 
one or more items, one of which is the Quantity itself, and others of 
which can describe the method of calculation and/or its (numeric) 
parameters, and would could encode the numeric parameters to describe 
the b-values of the original images. E.g., for an ADC map calculated 
from B0 and B1000 source images using a mono-exponential model one might 
encode something like:

(G-C1C6, SRT, "Quantity") = (113041, DCM, "Apparent Diffusion Coefficient")
(G-C036, SRT, "Measurement Method") = (xxxx0, 99XXX, "Monoexponential 
ADC from log of ratio of two samples")
(xxxx1, 99XXX, "Source image diffusion b-value") = 0
(xxxx1, 99XXX, "Source image diffusion b-value") = 1000

I have pre-coordinated the concepts of both the "source image" and the 
"diffusion b-value" into one code to use as the concept name of the 
numeric parameter, because we don't have a way to post-coordinate these 
to allow re-use of a code for just "b-value"; arguably we could just 
omit the "source image" component of the concept and just send "b-value" 
and the recipient could assume it was an input parameter (in the general 
case, this would reduce the combinatorial explosion of pre-coordinated 
codes).

Arguably one could omit mention of the b-value = 0 parameter, but in 
reviewing the old literature, I see that in the classic Burdette paper 
[1], a b-value of 1, not 0, was used.

Even some of the more complicated methods of computing ADC maps, such as 
these that involve different B values on a voxelwise basis, could be 
represented this way by listing all the collected b-values, even though 
one could not indicate which were used for which voxel (which would 
require another map). E.g., we might need methods such as:

"Monoexponential ADC from least squares fit of multiple samples"
"Monoexponential ADC from voxelwise selection of b-value"

See also [3].

Anyway, we should probably write a DICOM CP to add standard codes for 
the various methods and parameters.

We should probably consult with an MR physicist like Tom Chenevert 
and/or the QIBA MRI PDF group, to prepare a good list of methods and 
make sure we have captured the necessary parameters.

Before I forget to mention in, we also need to send the correct units in 
Measurement Units Code Sequence, which in UCUM are "mm2/s" (assuming all 
scaling issues have been appropriately dealt with [4], as should be the 
case for images you are creating).

David

1. Burdette JH, Elster AD, Ricci PE. Calculation of apparent diffusion 
coefficients (ADCs) in brain using two-point and six-point methods. J 
Comput Assist Tomogr. 1998 Oct;22(5):792–4. Available from: 
http://www.u.arizona.edu/~lewell/adc/article.html

2. Gatidis S, Schmidt H, Martirosian P, Nikolaou K, Schwenzer NF. 
Apparent diffusion coefficient-dependent voxelwise computed 
diffusion-weighted imaging: An approach for improving SNR and reducing 
T2 shine-through effects. Journal of Magnetic Resonance Imaging. 
2016;43(4):824–32. Available from: http://dx.doi.org/10.1002/jmri.25044

3. Park MY, Byun JY. Understanding the Mathematics Involved in 
Calculating Apparent Diffusion Coefficient Maps. American Journal of 
Roentgenology. 2012 Dec 1;199(6):W784–W784. Available from: 
http://dx.doi.org/10.2214/AJR.12.9231

4. Chenevert TL, Malyarenko DI, Newitt D, Li X, Jayatilake M, Tudorica 
A, et al. Errors in Quantitative Image Analysis due to 
Platform-Dependent Image Scaling. Translational Oncology. 2014 
Feb;7(1):65–71. Available from: 
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3998685/

**Comment by dclunie** [comment]
Answering my own question about the smallest b-value always being zero or not, turns out it isn't [5]:

"Why do most body and liver DWI protocols start with b-value 50 s/mm²? The selection of a low b-value larger than zero provides suppression of large vessels which makes lesions more conspicuous. The calculation of the tissue ADC can be more accurate when starting with even higher b-values like 100 or 200 to omit the contribution of flow and micro vascular effects."

Our DICOM CP should probably address how to encode the description of trace and exponential images as well.

David

5. Graessner J. Frequently Asked Questions: Diffusion-Weighted Imaging (DWI). MAGNETOM Flash. 2011 Jan; Available from: http://clinical-mri.com/wp-content/uploads/software_hardware_updates/Graessner.pdf

**Comment by dclunie** [comment]
Answering my own question about the smallest b-value always being zero 
or not, turns out it isn't [5]:

"Why do most body and liver DWI protocols start with b-value 50 s/mm²? 
The selection of a low b-value larger than zero provides suppression of 
large vessels which makes lesions more conspicuous. The calculation of 
the tissue ADC can be more accurate when starting with even higher 
b-values like 100 or 200 to omit the contribution of flow and micro 
vascular effects."

Our DICOM CP should probably address how to encode the description of 
trace and exponential images as well.

David

5. Graessner J. Frequently Asked Questions: Diffusion-Weighted Imaging 
(DWI). MAGNETOM Flash. 2011 Jan; Available from: 
http://clinical-mri.com/wp-content/uploads/software_hardware_updates/Graessner.pdf

**Comment by fedorov** [comment]
> Arguably one could omit mention of the b-value = 0 parameter

We should not, since in some instances, b0 can be skipped in the fitting process for various reasons.

**Comment by fedorov** [comment]
Communication to Dariya Malyarenko and Tom Chenevert, U. of Michigan, on Aug 3, 2016

> Dariya,
> 
> in order to properly encode ADC maps and results of fits, we need to
> "codify" the method used for fitting. For that, we need a list of
> methods that can be used for fitting, see more details here:
> https://github.com/QIICR/dcmqi/issues/54#issuecomment-237219341
> 
> I discussed this with David Clunie, and he suggested we ask Tom and/or
> QIBA MRI PDF group.
> 
> The models implemented in Slicer are the following:
> 
>  1) monoexponential fit
>  2) biexponential fit
>  3) kurtosis
>  4) stretched exponential
>  5) gamma model
> 
> For models (1-4), we could use this reference:
>
> Toivonen J., Merisaari H., Pesola M., Taimen P., Boström PJ., Pahikkala T., Aronen HJ., Jambor I. 2015. Mathematical models for diffusion-weighted imaging of prostate cancer using b values up to 2000 s/mm2: Correlation with Gleason score and repeatability of region of interest analysis. Magnetic resonance in medicine: official journal of the Society of Magnetic Resonance in Medicine / Society of Magnetic Resonance in Medicine 74:1116–1124. DOI: 10.1002/mrm.25482. 
>
> (or
> go more granular and trace the earlier papers for the individual
> models)
> 
> For 5, this one:
> 
> Oshio K., Shinmoto H., Mulkern RV. 2014. Interpretation of diffusion MR imaging data using a gamma distribution model. Magnetic resonance in medical sciences: MRMS: an official journal of Japan Society of Magnetic Resonance in Medicine 13:191–195. DOI: 10.2463/mrms.2014-0016.
> 
> Thinking about models that are not implemented in Slicer, there is
> "extrapolated perfusion fraction" from the paper David Newitt pointed
> me to: https://paperpile.com/app/p/329ed913-c02e-0229-b28d-a9d14ba8126c.
> 
> Do you have anything to add to this list, or any other suggestions?
>

**Comment by fedorov** [comment]
Response from Dariya, Aug 4

> Hi Andrey,
> 
> Tom and I discussed your suggested model list, and both DWI tissue models and corresponding references look sufficient.  These would be fine to "code" into DICOM as long as the code stays "expandable" (since new models may continue to come in.)
> 
> In addition to tissue model "functions", equally important relevant info (since source of variability) that we find currently missing concerns actual "fit algorithm", its constraints and parameters.  For instance, in case of multi-b-value DWI, the mono-exponential (single compartment) tissue model fit can be done in (at least) three ways: (1) mean of log-intensities for b=0,b>0 pairs; (2) linear least-squares for log-intensities of all b-values, or a sub-set of b-values; and (3)straight non-linear fit for exponential function.  The third option may also use different minimization algorithms (e.g., trust-region or Levenberg–Marquardt), with different constraints, addition of "S0" as a fit parameter, etc.
> 
> The tree of "fit-algorithm" possibilities grows proportional to model complexity for bi-exponential or other multi-compartment DWI models, and makes it important to have relevant info reflected in the DICOM of a produced parametric map.  For instance, taking into account fit algorithm, makes a "perfusion suppressed" ADC just a sub-type of bi-exponential "tissue model", with a "constrained linear fit", when D*>>ADC. Similar "algorithm classification" could be  used for any multi-b mono-exponential model fit, when b=0 is not acquired (e.g., b1>50). Also, certain fit algorithm have known limitations for the models, depending on DWI acquisition: e.g., "kurtosis" or "stretched exponential" nonlinear fit would "diverge" when b=0 is not acquired, etc.
> 
> We are not sure what is an appropriate way to "code" the "fit algorithm" information in parametric map  DICOM, but even having the text description would be helpful (as in David's example). The following MRM references cover some of the bi-exponential fit algorithm landscape that would be useful to include (Barbieri 2016; Neil 1993):
> http://onlinelibrary.wiley.com/doi/10.1002/mrm.25765/pdf
> http://onlinelibrary.wiley.com/doi/10.1002/mrm.1910290510/pdf

**Comment by fedorov** [comment]
This (at least b-values) use case has been addressed in the PRs above!
